### PR TITLE
Add mega-nav

### PR DESCRIPTION
**Pull request by sethvargo**
This is the first pass at adding the mega-nav. It's a three-step process, but it unifies all the code under one place should we want to make updates in the future.

If we like this approach, I'll need to make a new container and bump all the projects. Let me know what you think.

/cc @captainill @mitchellh

### CODE REVIEW

**Comment by mitchellh** [comment]
This LGTM. Its what I expected. ❤️

**Comment by captainill** [comment]
@sethvargo nice! That was quick. Looks like a great solution. 

What do updates to the mega_nav code necessitate to be published and available in the gem?

Then from the consumer side, assuming there are only changes to already declared/imported assets (HTML/CSS/JS), would you just need to update the gem and then 'middleman build'?

Thanks! Just wanna make sure I  understand how it works.

**Comment by sethvargo** [comment]
@captainill if you want to update the mega-nav, you update it here. Then we push a new version of the gem and update all the project sites.

**Comment by captainill** [comment]
@sethvargo ok thanks 👍

**Pull request merged**
