### PR TITLE
Changes "Solaris" to show up as "illumos", updates to "macOS".

### PR DESCRIPTION
**Pull request by slackpad**
Fixes https://github.com/hashicorp/consul/issues/2493 once we pull in an updated middleman in Consul

### CODE REVIEW

**Comment by sethvargo** [comment]
I think @jen20 had thoughts on this, but Go calls it "solaris", so we should call it "solaris" imo.

**Comment by slackpad** [comment]
I think he was the one to point out that Go screwed up the name :-) I just changed the display name so that the archive name still had Solaris so it maps to the name Go used for the OS.

**Comment by sethvargo** [comment]
@slackpad yea - that's my fear. The page will say "illumos", but the downloaded file will be `consul_0.6.0_solaris_amd64`, and I'm worried about the perception that could cause. "I downloaded Windows and got Mac". Maybe I'm overreacting and it's not a big deal, but I'd prefer these things to be consistent.

**Comment by jen20** [comment]
The problem is one of naming - the Go port is to Illumos _not_ Solaris. All the tests so far have shown that the Consul binary does not actually work on Solaris. Illumos is the correct term here.

**Comment by slackpad** [comment]
We could change the archive name as well - that would require some minor build scripting changes so then you'd get `consul_0.6.0_illumos_amd64`. Not sure if there's any benefit to keeping "solaris" in there so people know what Go settings were used to build it.

**Pull request closed without merging**
